config/routes.rb
Rails.application.routes.draw do

  post 'mailchimpsubscribe/subscribe' => 'mailchimpsubscribe#subscribe'

  root "pages#show", page: "pocetna"

  authenticate :user do
    get "/users" => "users#list", as: "list_users"
    get "/user/create_new" => "users#new_custom", as: "new_user"
    post "/user/create" => "users#create_custom", as: "users"
    delete "/user/delete/:id" => "users#delete_custom", as: "delete_user"

    # protect salon route
    get "/salon/:id/edit/prices" => "prices#advanced_edit", as: "edit_salon_price"
    post "/saloni" => "salons#create"
    get "/salon/new" => "salons#new", as: "new_salon"
    patch "/salon/:id" => "salons#update"
    put "/salon/:id" => "salons#update"
    delete "/salon/:id" => "salons#destroy"
    get "/salon/:id/edit" => "salons#edit", as: "edit_salon"

    # protect price routes
    resources :prices

    # protect service routes
    post "/usluge" => "services#create"
    get "/usluge" => "services#index", as: "services"
    get "/usluga/new" => "services#new", as: "new_service"
    get "/usluga/:id/edit" => "services#edit", as: "edit_service"
    patch "/usluga/:id" => "services#update"
    put "/usluga/:id" => "services#update"
    delete "/usluga/:id" => "services#destroy"

  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  # allow salon routes
  get "/saloni" => "salons#index", as: "salons"
  get "/saloni/pretraga" => "salons#search", as: "search_salons"
  get "/salon/:id" => "salons#show", as: "salon"

  # allow service routes
  get "/usluga/:id" => "services#show", as: "service"

  # allow pages routes
  get "/:page" => "pages#show"

end

app/models/salon.rb
class Salon < ActiveRecord::Base
  include Distance

  def to_param
    permalink
  end

  def self.search(search)
    where("name LIKE ? or address LIKE ? or city_name LIKE ? or municipality_name LIKE ?", "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
  end

  def distance_to(target)
    calculate_distance(self.lng, self.lat, target[:lng], target[:lat])
  end

  has_attached_file :image,
  :path => ":rails_root/public/system/:attachment/:id/:style-:filename",
  :url => "/system/:attachment/:id/:style-:filename",
  :styles => {
    :thumb    => ['100x100#',  :jpg, :quality => 70],
    :preview  => ['800x600#',  :jpg, :quality => 80],
    :large    => ['600>',      :jpg, :quality => 70],
    :retina   => ['1200>',     :jpg, :quality => 90]
  },
  :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip',
    :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
  }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :prices
  has_many :services, through: :prices

end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  before_filter :super_admin_permissions, only: [:new, :create,:destroy]
  before_filter :require_permission, only: [:edit, :update]


  def require_permission
    if current_user.control.to_i == 0
      return true
    end
    if @salon
      id = @salon.id
      if current_user.control.to_i == id or current_user.control.to_i == 0
        return true
      else
        flash[:alert] = t("no_right_to_do_that")
        redirect_to root_path
      end
    else
      flash[:alert] = t("no_right_to_do_that")
      redirect_to root_path
    end
  end

  def search
    @target = { :lng => cookies[:lng].to_f, :lat => cookies[:lat].to_f}
    @salons = Salon.all
    if params[:search]
      @salons = Salon.search(params[:search]).order("created_at DESC")
      if params[:sort]=='dalji'
        @salons = @salons.sort { |l,r| l.distance_to(@target) <=> r.distance_to(@target) }.reverse
      else
        @salons = @salons.sort { |l,r| l.distance_to(@target) <=> r.distance_to(@target) }
      end
    else
      @salons = Salon.all.order('created_at DESC')
    end
    @number_of_results = @salons.count
    @salons = @salons.paginate(:page => params[:strana])
  end

  def index
    @target = { :lng => cookies[:lng].to_f, :lat => cookies[:lat].to_f}

    if cookies[:lng] and cookies[:lat]
      @salons = Salon.all.sort { |l,r| l.distance_to(@target) <=> r.distance_to(@target) }
      if params[:sort]=="dalji"
        @salons = @salons.reverse
      end
    else
      @salons = Salon.all.order('updated_at DESC')
    end


    @number_of_results = @salons.count
    @salons = @salons.paginate(:page => params[:strana])
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)
    respond_to do |format|
      if @salon.save
        format.html { redirect_to @salon, notice: 'Salon was successfully created.' }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    respond_to do |format|
      id = @salon.id
      if current_user.control.to_i == id
        params = salon_params.except(:name, :permalink)
      end
      if current_user.control.to_i == 0
        params = salon_params
      end

      if @salon.update(params)
        format.html { redirect_to @salon, notice: 'Salon was successfully updated.' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.prices.each do |price|
      price.destroy
    end
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'Salon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find_by_permalink(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_params
      params.require(:salon).permit(
        :name,
        :address,
        :description,
        :lat, :lng,
        :permalink,
        :image,
        :phone1, :phone2,
        :email, :website,
        :facebook, :twitter, :instagram,
        :city_name, :municipality_name,
        :monday,
        :thusday,
        :wednesdey,
        :thursday,
        :friday,
        :saturday,
        :sunday)
    end
end

app/helpers/salons_helper.rb
module SalonsHelper
  def latest_salons
    @latest = Salon.all.order('created_at DESC').limit(4)
    return @latest
  end
end

app/views/salons/_form.html.haml
= form_for @salon,:html => {:class => 'form-horizontal'} do |f|
  - if @salon.errors.any?
    #error_explanation
      %h2
        = pluralize(@salon.errors.count, "error")
        prohibited this salon from being saved:
      %ul
        - @salon.errors.full_messages.each do |message|
          %li= message
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        Now editing:
        %b= @salon.name
        %span.pull-right
          - if @salon.permalink
            = link_to 'Edit prices', edit_salon_price_path(:id => @salon.permalink), :class => 'pull-right'
    .panel-body
      .form-group
        = f.label :image, :class => 'col-md-2 control-label'
        .col-md-10
          %img{:src => @salon.image}
          = f.file_field :image, :class => 'form-control'
      - if user_signed_in?
        - if current_user.control.to_i == 0
          .form-group
            = f.label :name, :class => 'col-md-2 control-label'
            .col-md-10
              = f.text_field :name, :class => "form-control", :required => true
          .form-group
            = f.label :permalink, :class => 'col-md-2 control-label'
            .col-md-10
              = f.text_field :permalink, :class => "form-control", :required => true
      .form-group
        = f.label :address, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :address, :class => "form-control", :required => true
      .form-group
        = f.label :city_name, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :city_name, :class => "form-control", :required => true
      .form-group
        = f.label :municipality_name, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :municipality_name, :class => "form-control", :required => true
      .form-group
        = f.label :phone1, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :phone1, :class => "form-control", :required => true
      .form-group
        = f.label :monday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :monday, :class => "form-control", :required => true
      .form-group
        = f.label :thusday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :thusday, :class => "form-control", :required => true
      .form-group
        = f.label :wednesdey, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :wednesdey, :class => "form-control", :required => true
      .form-group
        = f.label :thursday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :thursday, :class => "form-control", :required => true
      .form-group
        = f.label :friday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :friday, :class => "form-control", :required => true
      .form-group
        = f.label :saturday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :saturday, :class => "form-control", :required => true
      .form-group
        = f.label :sunday, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :sunday, :class => "form-control", :required => true
      .form-group
        = f.label :phone2, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :phone2, :class => "form-control", :required => true
      .form-group
        = f.label :email, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :email, :class => "form-control", :required => true
      .form-group
        = f.label :website, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :website, :class => "form-control", :required => true
      .form-group
        = f.label :facebook, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :facebook, :class => "form-control", :required => true
      .form-group
        = f.label :twitter, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :twitter, :class => "form-control", :required => true
      .form-group
        = f.label :instagram, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :instagram, :class => "form-control", :required => true
      .form-group
        = f.label :description, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_area :description, :rows => 5, :class => "form-control", :required => true
        - if f.object.lat.nil?
          - lat = 44.797638270
        - else
          - lat = f.object.lat
        - if f.object.lng.nil?
          - lng = 20.445800781
        - else
          - lng = f.object.lng
      .form-group.hidden
        = f.label :lat, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :lat, :class => "form-control", :value => lat
      .form-group.hidden
        = f.label :lng, :class => 'col-md-2 control-label'
        .col-md-10
          = f.text_field :lng, :class => "form-control", :value => lng
      .form-group
        %label.col-md-2.control-label Location:
        .col-md-10
          #map_canvas.form-control
      :javascript
        var map = new google.maps.Map(document.getElementById('map_canvas'), {
            zoom: 15,
            center: new google.maps.LatLng( #{lat} , #{lng} ),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var myMarker = new google.maps.Marker({
            position: new google.maps.LatLng( #{lat} , #{lng} ),
            draggable: true
        });

        google.maps.event.addListener(myMarker, 'dragend', function (evt) {
          var salon_lat = document.getElementById("salon_lat");
        salon_lat.value = evt.latLng.lat().toFixed(9);

        var salon_lng = document.getElementById("salon_lng");
        salon_lng.value = evt.latLng.lng().toFixed(9);
        });
        map.setCenter(myMarker.position);
        myMarker.setMap(map);
      .form-group
        .col-md-12
          .actions.text-right
            = f.submit 'Update', :class => 'btn btn-success'

app/views/salons/_salon_filter.html.haml
%div.col-md-6
  - if @number_of_results.to_i > 1
    - if (!current_page?(controller: 'salons', action: 'index') or !current_page?(controller: 'salons', action: 'search'))
      .dropdown.pull-right.search
        = t('sort_by')
        %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          -if defined?(@service)
            - if location_is_know
              - if params[:sort] == "blizi"
                bliže
              - if params[:sort] == "dalji"
                dalje
            - if params[:sort] == "skuplji"
              skuplje
            - if !params[:sort]
              jeftinije
          -else
            - if location_is_know
              - if params[:sort] == "dalji"
                dalje
              - else
                bliže
          %span.caret
        %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
          - if location_is_know
            -if defined?(@service)
              %li= link_to 'prvo bliže', url_for( params.merge(:sort => 'blizi').except(:strana)  )
            -else
              %li= link_to 'prvo bliže', url_for(:search => params[:search])
            %li= link_to 'prvo dalje', url_for( params.merge(:sort => 'dalji' ).except(:strana) )
          -if defined?(@service)
            %li= link_to 'prvo jeftinije', url_for()
            %li= link_to 'prvo skuplje', url_for( :sort => 'skuplji' )

app/views/salons/_salon_list.html.haml
.panel.panel-default.salon
  .panel-body
    .row
      .col-md-4
        - if salon.image.exists?
          = image_tag salon.image.url(:preview),:class => "salon_list_image"
        - else
          = image_tag("default.png", :class => "salon_list_image")
      .col-md-8
        %h3.title
          = salon.name
          - if location_is_know
            %span.pull-right.label.label-success
              = salon.distance_to(@target).round(2)
              %span km
          &nbsp;
          -if defined?(@service)
            %span.pull-right.label.label-default
              = salon.prices.find_by(service_id: @service.id).price
              %span RSD
        %span.address= salon.city_name
        ,
        %span.address= salon.municipality_name
        ,
        %span.address= salon.address
        %p= truncate(salon.description, :length => 200)
        .pull-right
          = link_to 'Pogledaj salon', salon,  class: "btn btn-default"
          - if is_admin(current_user)
            = link_to 'Edit', edit_salon_path(salon), class: "btn btn-primary"
            = link_to 'Destroy', salon, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/salons/edit.html.haml
= render 'form'

app/views/salons/index.html.haml
%div.row
  %div.col-md-6
    %h3.lead.pull-left.search
      Saloni
      %br
    %div.pull-left.search_count
      Ukupno salona:
      = @number_of_results
  -if location_is_know
    = render 'salons/salon_filter'
- @salons.each do |salon|
  = render 'salons/salon_list', salon: salon
= will_paginate @salons, :param_name => t('will_paginate.page'), renderer: BootstrapPagination::Rails
-if is_admin(current_user)
  = link_to 'New Salon', new_salon_path, class: "btn btn-success pull-right"

app/views/salons/new.html.haml
%h1 New Salon
= render 'form'
= link_to 'Back', salons_path

app/views/salons/search.html.haml
%div.row
  %div.col-md-6
    %h3.lead.pull-left.search
      Rezulati pretrage za:
      %b
        = params[:search]
      %br
    %div.pull-left.search_count
      Pronađeno salona:
      = @number_of_results
  -if location_is_know
    = render 'salons/salon_filter'
.clearfix
- @salons.each do |salon|
  = render 'salons/salon_list', salon: salon
= will_paginate @salons, :param_name => t('will_paginate.page'), renderer: BootstrapPagination::Rails
= link_to 'New Salon', new_salon_path, class: "btn btn-success pull-right"

app/views/salons/show.html.haml
.panel.panel-default
  .panel-body
    .row
      .col-md-4
        = image_tag @salon.image.url(:preview)
        %span.salon_info= @salon.address
        %a{ :href => "tel:"+@salon.phone1, :title => @salon.phone1, :class => 'salon_info' }
          = @salon.phone1
        %a{ :href => "tel:"+@salon.phone2, :title => @salon.phone2, :class => 'salon_info' }
          = @salon.phone2
        =mail_to @salon.email, @salon.email, :class => 'salon_info'
        %a{ :href => @salon.website, :title => @salon.website,:target => "_blank", :class => 'salon_info' }
          = @salon.website
        %a{ :href => @salon.facebook, :title => @salon.facebook,:target => "_blank", :class => 'salon_info' }
          = @salon.facebook
        %a{ :href => @salon.instagram, :title => @salon.instagram,:target => "_blank", :class => 'salon_info' }
          = @salon.instagram
        %a{ :href => @salon.twitter, :title => @salon.twitter,:target => "_blank",:class => 'salon_info' }
          = @salon.twitter
      .col-md-8
        %h1.salon_title
          = @salon.name
        = link_to 'Edit', edit_salon_path(@salon),class: "btn btn-info pull-right"
        %p= @salon.description
%h2
  Galerija
.panel.panel-default
  .panel-body
    .row
      = image_tag @salon.image.url(:preview), :class => 'col-md-3'
      = image_tag @salon.image.url(:preview), :class => 'col-md-3'
      = image_tag @salon.image.url(:preview), :class => 'col-md-3'
      = image_tag @salon.image.url(:preview), :class => 'col-md-3'

%h2
  Kako do nas
.panel.panel-default
  .panel-body
    .row
      .col-md-12
        #map_canvas{:style => "height:400px;min-height:10px;"}
:javascript
  var map = new google.maps.Map(document.getElementById('map_canvas'), {
      zoom: 15,
      center: new google.maps.LatLng( #{@salon.lat} , #{@salon.lng} ),
      mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var myMarker = new google.maps.Marker({
      position: new google.maps.LatLng( #{@salon.lat} , #{@salon.lng} ),
      draggable: true
  });

  google.maps.event.addListener(myMarker, 'dragend', function (evt) {
    var salon_lat = document.getElementById("salon_lat");
  salon_lat.value = evt.latLng.lat().toFixed(9);

  var salon_lng = document.getElementById("salon_lng");
  salon_lng.value = evt.latLng.lng().toFixed(9);
  });
  map.setCenter(myMarker.position);
  myMarker.setMap(map);