config/routes.rb
Rails.application.routes.draw do

  post 'mailchimpsubscribe/subscribe' => 'mailchimpsubscribe#subscribe'

  root "pages#show", page: "pocetna"

  authenticate :user do
    get "/users" => "users#list", as: "list_users"
    get "/user/create_new" => "users#new_custom", as: "new_user"
    post "/user/create" => "users#create_custom", as: "users"
    delete "/user/delete/:id" => "users#delete_custom", as: "delete_user"

    # protect salon route
    get "/salon/:id/edit/prices" => "prices#advanced_edit", as: "edit_salon_price"
    post "/saloni" => "salons#create"
    get "/salon/new" => "salons#new", as: "new_salon"
    patch "/salon/:id" => "salons#update"
    put "/salon/:id" => "salons#update"
    delete "/salon/:id" => "salons#destroy"
    get "/salon/:id/edit" => "salons#edit", as: "edit_salon"

    # protect price routes
    resources :prices

    # protect service routes
    post "/usluge" => "services#create"
    get "/usluge" => "services#index", as: "services"
    get "/usluga/new" => "services#new", as: "new_service"
    get "/usluga/:id/edit" => "services#edit", as: "edit_service"
    patch "/usluga/:id" => "services#update"
    put "/usluga/:id" => "services#update"
    delete "/usluga/:id" => "services#destroy"

  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  # allow salon routes
  get "/saloni" => "salons#index", as: "salons"
  get "/saloni/pretraga" => "salons#search", as: "search_salons"
  get "/salon/:id" => "salons#show", as: "salon"

  # allow service routes
  get "/usluga/:id" => "services#show", as: "service"

  # allow pages routes
  get "/:page" => "pages#show"

end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :salon
  belongs_to :service
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  before_filter :require_permission, only: [:new, :edit, :update, :destroy, :advanced_edit]


  def require_permission
    if current_user.control.to_i == 0
      return true
    end
    @salon = Salon.find_by_permalink(params[:id])
    if @salon
      id = @salon.id
    end
    if @price
      id = @price.salon.id
    end
    if current_user.control.to_i == id or current_user.control.to_i == 0
      return true
    else
      flash[:alert] = t("no_right_to_do_that")
      redirect_to root_path
    end
  end

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
    @test = 'test'
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  def advanced_edit
    @salon = Salon.find_by_permalink(params[:id])
    @prices = Price.where("salon_id = ?", @salon.id)
  end

  # GET /prices/1/edit
  def edit
  end

  # HELPER FUNCTION
  def update_services(price)
    current_service_id = price.service.id
    prices = Price.where(:service_id => current_service_id).count
    service_to_update = Service.find(current_service_id)
    service_to_update.update(:counter => prices)
  end

  # POST /prices
  # POST /prices.json
  def create
    if price_params[:salon_id].to_i == current_user.control.to_i or current_user.control.to_i == 0
      @price = Price.new(price_params)
      respond_to do |format|
        if @price.save
          update_services(@price)
          format.html { redirect_to :back, notice: '<b>' + @price.service.name + '</b> was successfully created.'}
          format.json { render :show, status: :created, location: @price }
        else
          format.html { render :back }
          format.json { render json: @price.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = t("no_right_to_do_that")
      redirect_to root_path
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to :back, notice: '<b>' + @price.service.name + '</b> was successfully updated.'}
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :back }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    update_services(@price)
    respond_to do |format|
      format.html { redirect_to :back, notice: '<b>' + @price.service.name + '</b> was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:price, :salon_id, :service_id)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_countservices.html.haml
- @services = Service.all
%ul.nav.nav-pills.nav-stacked
  - @services.each do |s|
    - if s.counter.to_i != 0
      - if request.env['PATH_INFO']==service_path(s)
        %li.current
          = link_to(s) do
            = s.name
            %span.badge.primary= s.counter
      - else
        %li
          = link_to(s) do
            = s.name
            %span.badge.primary= s.counter

app/views/prices/_form.html.haml
= form_for(@price) do |f|
  - if @price.errors.any?
    #error_explanation
      %h2
        = pluralize(@price.errors.count, "error")
        prohibited this price from being saved:
      %ul
        - @price.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :price
    %br
      = f.number_field :price
  .field
    = f.label :salon_id
    %br
      = f.select :salon_id, Salon.all.collect {|x| [x.name, x.id]}, {}
  .field
    = f.label :service_id
    %br
      = f.select :service_id, Service.all.collect {|x| [x.name, x.id]}, {}
  .actions
    = f.submit

app/views/prices/advanced_edit.html.haml
- @used_services = Array.new
.panel.panel-default
  .panel-heading
    %h3.panel-title
      Now editing services for salon:&nbsp;
      %b
        = link_to @salon.name, edit_salon_path
  .panel-body
    .row
      .col-md-12
        - if @prices
          - @prices.each do |price|
            = form_for price, :html => {:class => 'form-horizontal'} do |f|
              - if price.errors.any?
                #error_explanation
                  %h2
                    = pluralize(price.errors.count, "error")
                    prohibited this price from being saved:
                  %ul
                    - price.errors.full_messages.each do |message|
                      %li= message
              .form-group
                = f.label :price, :value => price.service.name, :class => 'col-md-2 control-label'
                .col-md-7
                  = f.number_field :price, :class => 'form-control'
                .col-md-3
                  = link_to 'Destroy', price, method: :delete,:class => 'control-label btn btn-danger', data: { confirm: 'Are you sure?' }
                  = f.submit 'Update', :class => 'control-label btn btn-success'
              .form-group.hidden
                = f.text_field :salon_id, :value => price.salon.id
                = f.text_field :service_id, :value => price.service.id
                - @used_services.push(price.service.id)

        - if @prices.count < 1
          %span This salon has no services at this time.

        - @options_for_select = Service.where.not(id: @used_services).collect {|x| [x.name, x.id]}
        -if @options_for_select.length > 0
          %hr
          = form_tag({:controller => 'prices'}, {:class => 'form-horizontal'}) do
            .form-group
              = label_tag 'price[service_id]', 'Service', class:'col-md-2 control-label'
              .col-md-4
                = select_tag('price[service_id]', options_for_select(@options_for_select), class: 'selectpicker', 'data-live-search': 'true', 'tabindex': "-99")
              .col-md-3
                = number_field_tag 'price[price]','', class: 'form-control'
              .col-md-3
                = submit_tag 'Add', class: 'control-label btn btn-success'
            .form-group.hidden
              = number_field_tag 'price[salon_id]', @salon.id
        -else
          .col-md-12
            %p.text-right No more available services. All services are currently assigned to this salon.

app/views/prices/edit.html.haml
%h1 Editing Price
= render 'form'
= link_to 'Show', @price
|
\#{link_to 'Back', prices_path}

app/views/prices/index.html.haml
%h1 Listing Prices
%table
  %thead
    %tr
      %th Price
      %th Salon
      %th Service
      %th{:colspan => "3"}
  %tbody
    - @prices.each do |price|
      %tr
        %td= price.price
        %td= price.salon.name
        %td= price.service.name
        %td= link_to 'Show', price
        %td= link_to 'Edit', edit_price_path(price)
        %td= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Price', new_price_path

app/views/prices/new.html.haml
%h1 New Price
= render 'form'
= link_to 'Back', prices_path

app/views/prices/show.html.haml
%p
  %strong Price:
  = @price.price
%p
  %strong Salon:
  = @price.salon.name
%p
  %strong Service:
  = @price.service.name
= link_to 'Edit', edit_price_path(@price)
|
\#{link_to 'Back', prices_path}