config/routes.rb
Rails.application.routes.draw do

  post 'mailchimpsubscribe/subscribe' => 'mailchimpsubscribe#subscribe'

  root "pages#show", page: "pocetna"

  authenticate :user do
    get "/users" => "users#list", as: "list_users"
    get "/user/create_new" => "users#new_custom", as: "new_user"
    post "/user/create" => "users#create_custom", as: "users"
    delete "/user/delete/:id" => "users#delete_custom", as: "delete_user"

    # protect salon route
    get "/salon/:id/edit/prices" => "prices#advanced_edit", as: "edit_salon_price"
    post "/saloni" => "salons#create"
    get "/salon/new" => "salons#new", as: "new_salon"
    patch "/salon/:id" => "salons#update"
    put "/salon/:id" => "salons#update"
    delete "/salon/:id" => "salons#destroy"
    get "/salon/:id/edit" => "salons#edit", as: "edit_salon"

    # protect price routes
    resources :prices

    # protect service routes
    post "/usluge" => "services#create"
    get "/usluge" => "services#index", as: "services"
    get "/usluga/new" => "services#new", as: "new_service"
    get "/usluga/:id/edit" => "services#edit", as: "edit_service"
    patch "/usluga/:id" => "services#update"
    put "/usluga/:id" => "services#update"
    delete "/usluga/:id" => "services#destroy"

  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  # allow salon routes
  get "/saloni" => "salons#index", as: "salons"
  get "/saloni/pretraga" => "salons#search", as: "search_salons"
  get "/salon/:id" => "salons#show", as: "salon"

  # allow service routes
  get "/usluga/:id" => "services#show", as: "service"

  # allow pages routes
  get "/:page" => "pages#show"

end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Beautysalons
    %link{:href => "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css",:rel => "stylesheet", :type => "text/css"}
    %link{:href => "//fonts.googleapis.com/css?family=Poiret+One|Lato:400,300,700,900&subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:src => "//maps.googleapis.com/maps/api/js"}
    %script{:src => "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"}
    = csrf_meta_tags
  %body
    .container
      .row
        .col-sm-6.col-md-4.col-md-offset-4
          .account-wall
            - if notice
              .alert.alert-success.col-sm-10.col-md-10.col-md-offset-1
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                = notice.html_safe
            - if alert
              .alert.alert-danger.col-sm-10.col-md-10.col-md-offset-1
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                = alert.html_safe
            = yield
            .text-center
              %br
              = link_to "Back", :back

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Beautysalons
    %link{:href => "//fonts.googleapis.com/css?family=Poiret+One|Lato:400,300,700,900&subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:src => "//maps.googleapis.com/maps/api/js"}
    %link{:href => "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css",:rel => "stylesheet", :type => "text/css"}
    %script{:src => "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"}
    = csrf_meta_tags
    - if user_signed_in?
      %body.admin
    - else
      %body
    :javascript
      $(document).ready(function() {
         $('.selectpicker').selectpicker();
          $('form#mailchimpsubscribe').bind("ajax:beforeSend", function(evt, xhr, settings){
            var $divResponse = $('div#response');

            // Update the text of the submit button to let the user know stuff is happening.
            // But first, store the original text of the submit button, so it can be restored when the request is finished.
            $divResponse.data( 'origText', $divResponse.text() );
            $divResponse.text( "Dodavanje email adrese u toku..." );

          })
          .bind("ajax:success", function(evt, data, status, xhr){
            var $form = $(this);
             var $divResponse = $('div#response');

            // Reset fields and any validation errors, so form can be used again, but leave hidden_field values intact.
            $form.find('input[type="email"]').val("");
            $divResponse.html(data.message);
          })
          .bind('ajax:complete', function(evt, xhr, status){
            var $divResponse = $('div#response');
          })
          .bind("ajax:error", function(evt, xhr, status, error){
             var $divResponse = $('div#response'),
                errors,
                errorText,
            errorList;

            try {
              // Populate errorText with the comment errors
              errors = $.parseJSON(xhr.responseText);
            } catch(err) {
              // If the responseText is not valid JSON (like if a 500 exception was thrown), populate errors with a generic error message.
              errors = {message: "Please reload the page and try again"};
            }

            // Build an unordered list from the list of errors
            errorText = "There were errors with the submission. Please reload the page and try again.";
            errorList = "<ul>"
            for ( error in errors ) {
              errorList += "<li>" + error + ': ' + errors[error] + "</li> ";
            }

            errorList += "</ul>";

            // Insert error list into form
            $divResponse.html(errorText);
          });
      });
      function removeLocation(){
        document.getElementById("removeLocation").innerHTML = '<span class="glyphicon glyphicon-refresh spinning"></span>Brisanje lokacije';
        url = window.location.toString();
        if(url.indexOf("#") > -1){
          url.replace("#", "");
        }
        if(url.indexOf("?sort=blizi") > -1){
          newlocation = url.replace("?sort=blizi", "");
        }
        else if(url.indexOf("&sort=blizi") > -1){
          newlocation = url.replace("&sort=blizi", "");
        }
        else if(url.indexOf("?sort=dalji") > -1){
          newlocation = url.replace("?sort=dalji", "");
        }
        else if(url.indexOf("&sort=dalji") > -1){
          newlocation = url.replace("&sort=dalji", "");
        }else{
          newlocation = url;
        }

        document.cookie = 'lat=;path=/;expires=Thu, 01 Jan 1970 00:00:01 GMT;';
        document.cookie = 'lng=;path=/;expires=Thu, 01 Jan 1970 00:00:01 GMT;';
        setTimeout(window.location = newlocation, 2500);

      }
      function getLocation() {
          document.getElementById("getLocation").innerHTML = '<span class="glyphicon glyphicon-refresh spinning"></span>Preuzimanje lokacije';

          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(showPosition);
          }
      }
      function showPosition(position) {
          // LAT
          document.cookie="lat="+position.coords.latitude+";path=/";
          console.log(position.coords.latitude);

          // LNG
          document.cookie="lng="+position.coords.longitude+";path=/";
          console.log(position.coords.longitude);

          // RELOAD PAGE TO IMPLEMENT CHANGES
          location.reload();
      }
    - if user_signed_in?
      .admin-menu-bar
        .container
          .row
            .col-md-6
              - if user_signed_in?
                Dobrodošli,
                %b
                  = current_user.email
                - if current_user.control.to_i != 0
                  - salon = Salon.all.find(current_user.control)
                  vaš salon je
                  %b
                    = link_to salon.name, edit_salon_path(salon)
                - else
                  vi ste
                  %b
                    SUPER ADMIN.
            .col-md-6.text-right
              - if user_signed_in?
                - if current_user.control.to_i == 0
                  = link_to "Dodaj usera", new_user_path
                  |
                  = link_to 'Svi korisnici', list_users_path
                  |
                  = link_to "Cene", prices_path
                  |
                  = link_to "Usluge", services_path
                  |
                = link_to 'Promena podataka', edit_user_registration_path
                |
                = link_to "Odjava", destroy_user_session_path, :method => :delete
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand.logo{:href => "/"}
            MOJA<span>LEPOTA</span>
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if !location_is_know
              %li
                %a{:id => "getLocation" , :href => "#", :onclick => "getLocation()"}
                  %span.glyphicon.glyphicon-map-marker
                  PREUZMI LOKACIJU
            - else
              %li
                %a{:id => "removeLocation" , :href => "#", :onclick => "removeLocation()"}
                  %span.glyphicon.glyphicon-map-marker
                  ZABORAVI LOKACIJU
            %li= link_to "Početna", '/'
            %li= link_to "O nama", '/o-nama'
            %li= link_to "Saloni", salons_path
            %li= link_to "Kontakt", '/kontakt'
            - if !user_signed_in?
              %li= link_to "Sign in", new_user_session_path
    .navbar.navbar-purple
      .container
        .row.search-form
          = form_tag(search_salons_path, :enforce_utf8 => false, :method => "get", id: "search-form", class: "row search-form") do
            .col-md-9
              = text_field_tag :search, params[:search], placeholder: "Pronađite salon po imenu, adresi, opštini ili telefonu"
            .col-md-3
              <button type="submit" class="search-button">PRONAĐI</button>
    .container
      .row
        .col-md-9
          - if notice
            .alert.alert-success
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              = notice.html_safe
          - if alert
            .alert.alert-danger
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              = alert.html_safe
          = yield
        %aside.col-md-3
          %h3.lead Usluge
          .panel.panel-default.panel-services
            .panel-body
              = render 'prices/countservices'
    %footer.navbar-inverse
      .container
        .row
          .col-md-3
            %h3.logo
              MOJA
              %span LEPOTA
            %p Dobrodošli na poral mojalepota.com! Ovaj portal namenjen je svima onima koji žele da pronađu kozmetičku uslugu po svojoj meri!
            %p Besplatnom registracijom, dobijate mogućnost pretrage salona i usluga i po udaljenosti! Kao i mogućnost praćenja salona i njihovih ponuda. Kao što smo rekli, registracija je potpuno besplatna.
          .col-md-3
            %h3 Budite u toku!
            %p Registrujte svoju email adresu koristeći kontakt formu, i budite uvek u toku sa najnovijim ponudama!
            = form_tag('/mailchimpsubscribe/subscribe', method: "post", id: "mailchimpsubscribe", class: "form-group", remote: "true") do
              = email_field(:email, :address, {id: "email", class: "form-control", placeholder: "Unesite ovde Vašu email adresu"})
              = submit_tag("PRIJAVA",:class => 'btn btn-default')
            .subscribe#response
          .col-md-3
            %h3 Najnoviji saloni
            %ul.latest_salons
              - latest_salons.each do |latest_salon|
                %a{ :href => salon_path(latest_salon), :title => latest_salon.name}
                  %li
                    %span.info.name
                      = latest_salon.name
                    %span.info.address
                      = latest_salon.address
                      ,
                    %span.info.municipality
                      = latest_salon.municipality_name
                      ,
                    %span.info.city
                      = latest_salon.city_name
          .col-md-3
            %h3 Kontakt
            %table.table.contact
              %tr
                %td
                  %span.glyphicon.glyphicon-map-marker>
                  Adresa:
                %td
                  Karađorđeva 6/153
                  %br 11080, Beograd, Srbija
              %tr
                %td
                  %span.glyphicon.glyphicon-envelope>
                  Email:
                %td office@mojalepota.com
              %tr
                %td
                  %span.glyphicon.glyphicon-phone>
                  Telefon:
                %td +381 (60) 6629 - 098
              %tr
                %td
                  %span.glyphicon.glyphicon-headphones>
                  Podrška:
                %td
                  +381 (60) 6629 - 098
                  %br podrska@mojalepota.com
    .copyright
      .container
        .row
          .col-md-6.text-left
            Developed by PIXEL2GO.COM
          .col-md-6.text-right
            2015 &copy; All rights recieved.